---
- name: install supervisor
  apt:
    name: supervisor
    state: present


- name: Copy supervisor_gunicorn config (this file will run Gunicorn)
  template:
    src: supervisor_gunicorn.j2
    dest: "/etc/supervisor/conf.d/supervisor_gunicorn.conf"


- name: Copy supervisor_daphne config (this file will run Daphne)
  template:
    src: supervisor_daphne.j2
    dest: "/etc/supervisor/conf.d/supervisor_daphne.conf"
  # become_user: "{{ project_user }}"


- name: Start supervisor
  systemd:
    name: supervisor
    state: restarted
    # demon_reload: yes
    # enabled: yes

- name: Add firewall rule Allow 9002
  community.general.ufw:
  # state: disabled
    state: enabled
    rule: allow
    port: '9002'
  # proto: tcp
    # delete: yes