- hosts: hostgroups
  gather_facts: no
  # become_method: su

  become: True
  roles:

    # CREATE PROJECT USER
    - role: 'deploy/django-demo-app/project-user'
      vars: 
        # is used by: project-user, app
        project_user: "django"  
      tags: create_project_user
    
    # CREATE DATABASE
    - role: 'deploy/django-demo-app/db'
      vars:
        db_port: 5432
        db_user: "user1"
        db_pass: "my_pass"
        db_name: "database1"
      tags: db

    # CONFIG DJANGO PROJECT
    - role: 'deploy/django-demo-app/app'
      vars: 
        # is used by: project-user, app
        project_dir: "/home/{{ project_user }}/project"  
      tags: app

    # NGINX
    - role: 'deploy/django-demo-app/nginx'
      vars:
        gunicorn_port: 9001
      tags: nginx
    
    # GUNICORN
    - role: 'deploy/django-demo-app/gunicorn'
      vars:
        gunicorn_port: 9001
      tags: gunicorn
    
    # SUPERVISOR
    - role: 'deploy/django-demo-app/supervisor' 
      tags: supervisor