---
- name: Create main dirs for {{etcdir}}
  file:
    path: "{{ etcdir }}"
    state: directory

- name: Copy gunicorn configs
  template:
    src: gunicorn.conf.py
    dest: "{{ etcdir }}/gunicorn.conf.py"

- nema: Copy gunicorn enviroment file
  template:
    src: gunicorn.env
    dest: "{{ etcdir }}/gunicorn.env"
  
- name: Copy gunicorn system unit
  template:
    src: project_name.service
    dest: /etc/systemd/system/project_name.service

- name: Restart c service
  systemd:
    name: project_name
    state: restarted
    demon_reload: yes
    enabled: yes